title: <h1>test</h1>
description: test
template:
  repo: <h1>test</h1>
  name: lessh1greatertestlessh1greater
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
